// Auto-generated by @daldalso/tailwind-base
/* eslint-disable */
"use client";
import { loadTailwindBase } from "@daldalso/tailwind-base";
import { tailwindBaseConfig } from ".";
import React from "react";
export default function ClientTailwindBaseInitializer(){
  React.useMemo(() => loadTailwindBase(tailwindBaseConfig), []);
  return null;
}